# Generated by Django 5.0.6 on 2026-06-30 12:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(help_text='10-digit mobile number', max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid 10-digit mobile number.', regex='^\\d{10}$')])),
                ('aadhar_number', models.CharField(help_text='12-digit Aadhar number', max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid 12-digit Aadhar number.', regex='^\\d{12}$')])),
                ('bill_number', models.CharField(help_text='Bill / Invoice number from purchase', max_length=50, unique=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('has_played', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ['-registered_at'],
            },
        ),
    ]
