# Generated by Django 5.0.6 on 2026-06-30 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['-registered_at'], name='customer_registered_at_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['has_played'], name='customer_has_played_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['registered_at', 'has_played'], name='customer_reg_played_idx'),
        ),
    ]
